spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址（最后不需要带/，否则会出现：No custom http config found for URL: XXX）
          uri: https://github.com/GitHub-70/ideaworkspace-springcloud
          # git仓库地址下的相对搜索地址（可用使用通配符），可以配置多个，用,分割。可以{application}实现按应用查配置
          searchPaths: config-file/src
#          username: your-username  # git仓库的账号（公开仓库无需账号信息）
#          password: your-password  # git仓库的密码（公开仓库无需账号信息）
          # git默认分支
          default-label: master

server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:2001/eureka, http://eureka-2:2002/eureka