spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/GitHub-70/ideaworkspace-springcloud/
          searchPaths: config-file/src
          #username: your-username
          #password: your-password

server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:2001/eureka, http://eureka-2:2002/eureka