spring:
  profiles:
    active: local-1

# 用户自定义属性
sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

# http://localhost:8101/actuator/refresh 不支持GET请求
management:
  endpoints:
    web:
      exposure:
        include: refresh
---

spring:
  application:
    name: user-server1
  profiles: local-1

server:
  port: 8101


eureka:
  client:
    service-url:
      # 每个服务单元向注册中心 eureka-1:2001 登记自己提供的服务
      defaultZone: http://eureka-1:2001/eureka #defaultZone 表示服务器的部署位置
  instance:
    # 心跳超时时间10s，默认90s。从client端最后一次发出心跳后，
    # 达到这个时间没有再次发出心跳，表示服务不可用，将它的实例从注册中心移除
    lease-expiration-duration-in-seconds: 10
    # 心跳间隔4s，默认30s。每一个服务配置后，心跳间隔和心跳超时时间会被保存在server端，
    # 不同服务的心跳频率可能不同，server端会根据保存每个实例的配置来分别探活
    lease-renewal-interval-in-seconds: 4

---
spring:
  application:
    name: user-server2
  profiles: local-2

server:
  port: 8102


eureka:
  client:
    service-url:
      # 每个服务单元向注册中心 eureka-1:2001 登记自己提供的服务
      defaultZone: http://eureka-1:2001/eureka #defaultZone 表示服务器的部署位置
  instance:
    # 心跳超时时间10s，默认90s。从client端最后一次发出心跳后，
    # 达到这个时间没有再次发出心跳，表示服务不可用，将它的实例从注册中心移除
    lease-expiration-duration-in-seconds: 10
    # 心跳间隔4s，默认30s。每一个服务配置后，心跳间隔和心跳超时时间会被保存在server端，
    # 不同服务的心跳频率可能不同，server端会根据保存每个实例的配置来分别探活
    lease-renewal-interval-in-seconds: 4