spring:
  application:
    name: feign

server:
  port: 3003

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:2001/eureka, http://eureka-2:2002/eureka
# ribbon 全局配置
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000

# 针对某个实例 进行 ribbon 配置
item-server:
  ribbon:
    # 连接 1 秒超时
    ConnectTimeout: 1000
    # 读取超时时间 1 秒
    ReadTimeout: 1000
    # 当前实例请求失败，重试其他实例次数
    MaxAutoRetriesNextServer: 1
    # 当前实例重试请求次数
    MaxAutoRetries: 0
    # 是否对所有操作都进行重试
    OkToRetryOnAllOperations: false
  # hystrix的超时时间
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 2000



# todo 待研究
#hystrix:
#  metrics:
#    # 启动 hystrix 熔断降级
#    enabled: true
#    polling-interval-ms: 500 #时间间隔 默认10秒

feign:
#  metrics:
#    enabled: true
  # 启动 hystrix 降级熔断
  # todo 只要第一次未请求数据成功，断点打开，直接走降级服务
  # @EnableCircuitBreaker只针对Hystrix 对Feign没用，所以必须在feign配置下启动hystrix
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        # 暴露的端点 health，info，hystrix.stream
        # 通过http://localhost:3003/actuator  来展示所有通过HTTP暴露的endpoints。
        # hystrix.stream 该端点信息，需要有 hystrix 依赖，以及启动 hystrix
        include: health, info, hystrix.tream



