spring:
    application:
        name: ribbon

server:
    port: 3001


eureka:
    client:
        service-url:
            # 每个服务单元向注册中心 eureka-1:2001 登记自己提供的服务
            defaultZone: http://eureka-1:2001/eureka,http://eureka-2:2002/eureka #defaultZone 表示服务器的部署位置

# 无效版本 虽然重试了，但只访问了一次
ribbon:
    # 更换实例的次数
    MaxAutoRetriesNextServer: 3
    # 当前实例重试次数，尝试失败会更换下一个实例
    MaxAutoRetries: 2
    # 重试所有操作(连接、读取超时)
    OkToRetryOnAllOperations: true

#ribbon:
#    eureka:
#        enabled: true
